name: 'env-hopper'
services:
  env-hopper-preview:
    build:
      context: .
    restart: unless-stopped
    ports:
      - "4002:4002"
    container_name: env-hopper-preview
    volumes:
      - ./db:/var/db/
    environment:
      PORT: 4002
