linkWorkspacePackages: true
#injectWorkspacePackage: true

packages:
  - packages/*
  - examples/*

catalog:
  '@prisma/client': ^6.9.0
  '@tanstack/config': ^0.20.1
  '@tanstack/query-sync-storage-persister': ^5.80.6
  '@tanstack/react-query': ^5.80.3
  '@tanstack/react-router': ^1.131.27
  '@tanstack/react-router-devtools': 1.131.27
  '@tanstack/react-virtual': ^3.13.0
  '@tanstack/router-plugin': 1.131.27
  '@testing-library/jest-dom': ^6.5.0
  '@testing-library/react': ^16.2.0
  '@trpc/client': ^11.4.2
  '@trpc/server': ^11.4.2
  '@trpc/tanstack-react-query': ^11.4.2
  '@types/dotenv-defaults': ^2.0.4
  '@types/express': ^5.0.0
  '@types/node': ^24.3.0
  '@types/react': ^19.0.8
  '@types/react-dom': ^19.1.6
  '@typescript-eslint/eslint-plugin': ^8.42.0
  '@typescript-eslint/parser': ^8.42.0
  '@vitejs/plugin-react': ^4.3.4
  '@vitest/ui': 3.2.2
  cross-env: ^7.0.3
  dotenv-defaults: 5.0.2
  esbuild: ^0.25.5
  eslint: ^9.22.0
  eslint-plugin-import: 2.31.0
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-unused-imports: ^4.2.0
  express: ^5.1.0
  radashi: 12.5.0-beta.6d5c035
  react: 19.1.0
  react-dom: 19.1.0
  tslib: ^2.3.0
  tsx: ^4.19.4
  typescript: 5.8.3
  typescript-eslint: ^8.42.0
  vite: ^6.3.5
  vite-plugin-node: ^5.0.1
  vite-plugin-pwa: ^1.0.0
  vite-plugin-static-copy: ^3.1.4
  vite-plugin-svgr: ^4.2.0
  vitest: 3.2.2
  zod: ^3.25.49
  vite-tsconfig-paths: '^5.1.4'
  tailwindcss: '^4.1.7'
  '@tailwindcss/vite': ^4.0.5
