/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutEnvEnvSlugIndexRouteImport } from './routes/_layout/env.$envSlug.index'
import { Route as LayoutAppAppSlugIndexRouteImport } from './routes/_layout/app.$appSlug.index'
import { Route as LayoutEnvEnvSlugAppAppSlugIndexRouteImport } from './routes/_layout/env.$envSlug.app.$appSlug.index'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEnvEnvSlugIndexRoute = LayoutEnvEnvSlugIndexRouteImport.update({
  id: '/env/$envSlug/',
  path: '/env/$envSlug/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAppAppSlugIndexRoute = LayoutAppAppSlugIndexRouteImport.update({
  id: '/app/$appSlug/',
  path: '/app/$appSlug/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEnvEnvSlugAppAppSlugIndexRoute =
  LayoutEnvEnvSlugAppAppSlugIndexRouteImport.update({
    id: '/env/$envSlug/app/$appSlug/',
    path: '/env/$envSlug/app/$appSlug/',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/app/$appSlug': typeof LayoutAppAppSlugIndexRoute
  '/env/$envSlug': typeof LayoutEnvEnvSlugIndexRoute
  '/env/$envSlug/app/$appSlug': typeof LayoutEnvEnvSlugAppAppSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/app/$appSlug': typeof LayoutAppAppSlugIndexRoute
  '/env/$envSlug': typeof LayoutEnvEnvSlugIndexRoute
  '/env/$envSlug/app/$appSlug': typeof LayoutEnvEnvSlugAppAppSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/app/$appSlug/': typeof LayoutAppAppSlugIndexRoute
  '/_layout/env/$envSlug/': typeof LayoutEnvEnvSlugIndexRoute
  '/_layout/env/$envSlug/app/$appSlug/': typeof LayoutEnvEnvSlugAppAppSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app/$appSlug'
    | '/env/$envSlug'
    | '/env/$envSlug/app/$appSlug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/app/$appSlug' | '/env/$envSlug' | '/env/$envSlug/app/$appSlug'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/'
    | '/_layout/app/$appSlug/'
    | '/_layout/env/$envSlug/'
    | '/_layout/env/$envSlug/app/$appSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/env/$envSlug/': {
      id: '/_layout/env/$envSlug/'
      path: '/env/$envSlug'
      fullPath: '/env/$envSlug'
      preLoaderRoute: typeof LayoutEnvEnvSlugIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/app/$appSlug/': {
      id: '/_layout/app/$appSlug/'
      path: '/app/$appSlug'
      fullPath: '/app/$appSlug'
      preLoaderRoute: typeof LayoutAppAppSlugIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/env/$envSlug/app/$appSlug/': {
      id: '/_layout/env/$envSlug/app/$appSlug/'
      path: '/env/$envSlug/app/$appSlug'
      fullPath: '/env/$envSlug/app/$appSlug'
      preLoaderRoute: typeof LayoutEnvEnvSlugAppAppSlugIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAppAppSlugIndexRoute: typeof LayoutAppAppSlugIndexRoute
  LayoutEnvEnvSlugIndexRoute: typeof LayoutEnvEnvSlugIndexRoute
  LayoutEnvEnvSlugAppAppSlugIndexRoute: typeof LayoutEnvEnvSlugAppAppSlugIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutAppAppSlugIndexRoute: LayoutAppAppSlugIndexRoute,
  LayoutEnvEnvSlugIndexRoute: LayoutEnvEnvSlugIndexRoute,
  LayoutEnvEnvSlugAppAppSlugIndexRoute: LayoutEnvEnvSlugAppAppSlugIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
