/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminChatRouteImport } from './routes/admin/chat'
import { Route as LayoutLoginRouteImport } from './routes/_layout/login'
import { Route as LayoutEnvsIndexRouteImport } from './routes/_layout/envs.index'
import { Route as LayoutDashboardIndexRouteImport } from './routes/_layout/dashboard.index'
import { Route as LayoutEnvEnvSlugIndexRouteImport } from './routes/_layout/env.$envSlug.index'
import { Route as LayoutAppAppSlugIndexRouteImport } from './routes/_layout/app.$appSlug.index'
import { Route as LayoutEnvEnvSlugSubSubValueIndexRouteImport } from './routes/_layout/env.$envSlug.sub.$subValue.index'
import { Route as LayoutEnvEnvSlugAppAppSlugIndexRouteImport } from './routes/_layout/env.$envSlug.app.$appSlug.index'
import { Route as LayoutAppAppSlugSubSubValueIndexRouteImport } from './routes/_layout/app.$appSlug.sub.$subValue.index'
import { Route as LayoutEnvEnvSlugAppAppSlugSubSubValueIndexRouteImport } from './routes/_layout/env.$envSlug.app.$appSlug.sub.$subValue.index'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChatRoute = AdminChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AdminRoute,
} as any)
const LayoutLoginRoute = LayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEnvsIndexRoute = LayoutEnvsIndexRouteImport.update({
  id: '/envs/',
  path: '/envs/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardIndexRoute = LayoutDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEnvEnvSlugIndexRoute = LayoutEnvEnvSlugIndexRouteImport.update({
  id: '/env/$envSlug/',
  path: '/env/$envSlug/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAppAppSlugIndexRoute = LayoutAppAppSlugIndexRouteImport.update({
  id: '/app/$appSlug/',
  path: '/app/$appSlug/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEnvEnvSlugSubSubValueIndexRoute =
  LayoutEnvEnvSlugSubSubValueIndexRouteImport.update({
    id: '/env/$envSlug/sub/$subValue/',
    path: '/env/$envSlug/sub/$subValue/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutEnvEnvSlugAppAppSlugIndexRoute =
  LayoutEnvEnvSlugAppAppSlugIndexRouteImport.update({
    id: '/env/$envSlug/app/$appSlug/',
    path: '/env/$envSlug/app/$appSlug/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAppAppSlugSubSubValueIndexRoute =
  LayoutAppAppSlugSubSubValueIndexRouteImport.update({
    id: '/app/$appSlug/sub/$subValue/',
    path: '/app/$appSlug/sub/$subValue/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutEnvEnvSlugAppAppSlugSubSubValueIndexRoute =
  LayoutEnvEnvSlugAppAppSlugSubSubValueIndexRouteImport.update({
    id: '/env/$envSlug/app/$appSlug/sub/$subValue/',
    path: '/env/$envSlug/app/$appSlug/sub/$subValue/',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LayoutLoginRoute
  '/admin/chat': typeof AdminChatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof LayoutDashboardIndexRoute
  '/envs/': typeof LayoutEnvsIndexRoute
  '/app/$appSlug/': typeof LayoutAppAppSlugIndexRoute
  '/env/$envSlug/': typeof LayoutEnvEnvSlugIndexRoute
  '/app/$appSlug/sub/$subValue/': typeof LayoutAppAppSlugSubSubValueIndexRoute
  '/env/$envSlug/app/$appSlug/': typeof LayoutEnvEnvSlugAppAppSlugIndexRoute
  '/env/$envSlug/sub/$subValue/': typeof LayoutEnvEnvSlugSubSubValueIndexRoute
  '/env/$envSlug/app/$appSlug/sub/$subValue/': typeof LayoutEnvEnvSlugAppAppSlugSubSubValueIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LayoutLoginRoute
  '/admin/chat': typeof AdminChatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof LayoutIndexRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof LayoutDashboardIndexRoute
  '/envs': typeof LayoutEnvsIndexRoute
  '/app/$appSlug': typeof LayoutAppAppSlugIndexRoute
  '/env/$envSlug': typeof LayoutEnvEnvSlugIndexRoute
  '/app/$appSlug/sub/$subValue': typeof LayoutAppAppSlugSubSubValueIndexRoute
  '/env/$envSlug/app/$appSlug': typeof LayoutEnvEnvSlugAppAppSlugIndexRoute
  '/env/$envSlug/sub/$subValue': typeof LayoutEnvEnvSlugSubSubValueIndexRoute
  '/env/$envSlug/app/$appSlug/sub/$subValue': typeof LayoutEnvEnvSlugAppAppSlugSubSubValueIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_layout/login': typeof LayoutLoginRoute
  '/admin/chat': typeof AdminChatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_layout/': typeof LayoutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_layout/dashboard/': typeof LayoutDashboardIndexRoute
  '/_layout/envs/': typeof LayoutEnvsIndexRoute
  '/_layout/app/$appSlug/': typeof LayoutAppAppSlugIndexRoute
  '/_layout/env/$envSlug/': typeof LayoutEnvEnvSlugIndexRoute
  '/_layout/app/$appSlug/sub/$subValue/': typeof LayoutAppAppSlugSubSubValueIndexRoute
  '/_layout/env/$envSlug/app/$appSlug/': typeof LayoutEnvEnvSlugAppAppSlugIndexRoute
  '/_layout/env/$envSlug/sub/$subValue/': typeof LayoutEnvEnvSlugSubSubValueIndexRoute
  '/_layout/env/$envSlug/app/$appSlug/sub/$subValue/': typeof LayoutEnvEnvSlugAppAppSlugSubSubValueIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/chat'
    | '/auth/callback'
    | '/admin/'
    | '/dashboard/'
    | '/envs/'
    | '/app/$appSlug/'
    | '/env/$envSlug/'
    | '/app/$appSlug/sub/$subValue/'
    | '/env/$envSlug/app/$appSlug/'
    | '/env/$envSlug/sub/$subValue/'
    | '/env/$envSlug/app/$appSlug/sub/$subValue/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/admin/chat'
    | '/auth/callback'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/envs'
    | '/app/$appSlug'
    | '/env/$envSlug'
    | '/app/$appSlug/sub/$subValue'
    | '/env/$envSlug/app/$appSlug'
    | '/env/$envSlug/sub/$subValue'
    | '/env/$envSlug/app/$appSlug/sub/$subValue'
  id:
    | '__root__'
    | '/_layout'
    | '/admin'
    | '/_layout/login'
    | '/admin/chat'
    | '/auth/callback'
    | '/_layout/'
    | '/admin/'
    | '/_layout/dashboard/'
    | '/_layout/envs/'
    | '/_layout/app/$appSlug/'
    | '/_layout/env/$envSlug/'
    | '/_layout/app/$appSlug/sub/$subValue/'
    | '/_layout/env/$envSlug/app/$appSlug/'
    | '/_layout/env/$envSlug/sub/$subValue/'
    | '/_layout/env/$envSlug/app/$appSlug/sub/$subValue/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/chat': {
      id: '/admin/chat'
      path: '/chat'
      fullPath: '/admin/chat'
      preLoaderRoute: typeof AdminChatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_layout/login': {
      id: '/_layout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LayoutLoginRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/envs/': {
      id: '/_layout/envs/'
      path: '/envs'
      fullPath: '/envs/'
      preLoaderRoute: typeof LayoutEnvsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard/': {
      id: '/_layout/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof LayoutDashboardIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/env/$envSlug/': {
      id: '/_layout/env/$envSlug/'
      path: '/env/$envSlug'
      fullPath: '/env/$envSlug/'
      preLoaderRoute: typeof LayoutEnvEnvSlugIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/app/$appSlug/': {
      id: '/_layout/app/$appSlug/'
      path: '/app/$appSlug'
      fullPath: '/app/$appSlug/'
      preLoaderRoute: typeof LayoutAppAppSlugIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/env/$envSlug/sub/$subValue/': {
      id: '/_layout/env/$envSlug/sub/$subValue/'
      path: '/env/$envSlug/sub/$subValue'
      fullPath: '/env/$envSlug/sub/$subValue/'
      preLoaderRoute: typeof LayoutEnvEnvSlugSubSubValueIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/env/$envSlug/app/$appSlug/': {
      id: '/_layout/env/$envSlug/app/$appSlug/'
      path: '/env/$envSlug/app/$appSlug'
      fullPath: '/env/$envSlug/app/$appSlug/'
      preLoaderRoute: typeof LayoutEnvEnvSlugAppAppSlugIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/app/$appSlug/sub/$subValue/': {
      id: '/_layout/app/$appSlug/sub/$subValue/'
      path: '/app/$appSlug/sub/$subValue'
      fullPath: '/app/$appSlug/sub/$subValue/'
      preLoaderRoute: typeof LayoutAppAppSlugSubSubValueIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/env/$envSlug/app/$appSlug/sub/$subValue/': {
      id: '/_layout/env/$envSlug/app/$appSlug/sub/$subValue/'
      path: '/env/$envSlug/app/$appSlug/sub/$subValue'
      fullPath: '/env/$envSlug/app/$appSlug/sub/$subValue/'
      preLoaderRoute: typeof LayoutEnvEnvSlugAppAppSlugSubSubValueIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutLoginRoute: typeof LayoutLoginRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutDashboardIndexRoute: typeof LayoutDashboardIndexRoute
  LayoutEnvsIndexRoute: typeof LayoutEnvsIndexRoute
  LayoutAppAppSlugIndexRoute: typeof LayoutAppAppSlugIndexRoute
  LayoutEnvEnvSlugIndexRoute: typeof LayoutEnvEnvSlugIndexRoute
  LayoutAppAppSlugSubSubValueIndexRoute: typeof LayoutAppAppSlugSubSubValueIndexRoute
  LayoutEnvEnvSlugAppAppSlugIndexRoute: typeof LayoutEnvEnvSlugAppAppSlugIndexRoute
  LayoutEnvEnvSlugSubSubValueIndexRoute: typeof LayoutEnvEnvSlugSubSubValueIndexRoute
  LayoutEnvEnvSlugAppAppSlugSubSubValueIndexRoute: typeof LayoutEnvEnvSlugAppAppSlugSubSubValueIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutLoginRoute: LayoutLoginRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutDashboardIndexRoute: LayoutDashboardIndexRoute,
  LayoutEnvsIndexRoute: LayoutEnvsIndexRoute,
  LayoutAppAppSlugIndexRoute: LayoutAppAppSlugIndexRoute,
  LayoutEnvEnvSlugIndexRoute: LayoutEnvEnvSlugIndexRoute,
  LayoutAppAppSlugSubSubValueIndexRoute: LayoutAppAppSlugSubSubValueIndexRoute,
  LayoutEnvEnvSlugAppAppSlugIndexRoute: LayoutEnvEnvSlugAppAppSlugIndexRoute,
  LayoutEnvEnvSlugSubSubValueIndexRoute: LayoutEnvEnvSlugSubSubValueIndexRoute,
  LayoutEnvEnvSlugAppAppSlugSubSubValueIndexRoute:
    LayoutEnvEnvSlugAppAppSlugSubSubValueIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface AdminRouteChildren {
  AdminChatRoute: typeof AdminChatRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminChatRoute: AdminChatRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
