export const autocompleteData = [
  { app: 'LIMS', group: 'prodlims', title: 'Home' },
  { app: 'LIMS', group: 'prodlims', title: 'Script Console Prod-Lims' },
  { app: 'LIMS', group: 'prodlims', title: 'Script Console Prod-Lims (Predefined)' },
  { app: 'LIMS', group: 'prodlims', title: 'RM Support Review case #' },
  { app: 'LIMS', group: 'prodlims', title: 'View case #' },
  { app: 'LIMS', group: 'extranet', title: 'Home' },
  { app: 'LIMS', group: 'extranet', title: 'Console' },
  { app: 'LIMS', group: 'extranet', title: 'Referral case #' },
  { app: 'LIMS', group: 'extranet', title: 'Edit organization/clinic #' },
  { app: 'LIMS', group: 'extranet', title: 'Data entry' },
  { app: 'LIMS', group: 'accessioning', title: 'SlipStream Dashboard' },
  { app: 'Kafka UI', group: 'kafka-ui', title: 'Topics' },
  { app: 'Kafka UI', group: 'kafka-ui', title: 'topic #' },
  { app: 'Kafka UI', group: 'kafka-ui', title: 'casefile-id-aggregator' },
  { app: 'Kafka UI', group: 'kafka-ui', title: 'casefile-id-aggregator Case #' },
  { app: 'Sample Review App 1.0', group: 'sra-web-ui', title: 'Home' },
  { app: 'Sample Review App 1.0', group: 'sra-web-ui', title: 'Case #' },
  { app: 'Sample Review App 2.0', group: 'sra2', title: 'Home' },
  { app: 'Sample Review App 2.0', group: 'sra2', title: 'Order #' },
  { app: 'Connect App (Rancher)', group: 'connect', title: 'Home' },
  { app: 'Connect App (Rancher)', group: 'connect', title: 'Case #' },
  { app: 'LabVantage 1.0', group: null, title: 'Home' },
  { app: 'LabVantage 1.0', group: null, title: 'Console' },
  { app: 'Lab Operations Platform', group: null, title: 'Home' },
  { app: 'Lab Operations Platform', group: null, title: 'Console' },
  { app: 'Signatera Portal (Oncology)', group: null, title: 'Home' },
  { app: 'Signatera Portal (Oncology)', group: null, title: 'Order #' },
  { app: 'RUO Upload Tool', group: null, title: 'Upload Dashboard' },
  { app: 'IDEA UI (Data Entry)', group: null, title: 'Data Entry' },
  { app: 'Production Review', group: null, title: 'Production Dashboard' }
];
